### ISSUE TITLE
Cartpole example error with pfrl_ppo_train.py

### ISSUE THREAD

**Issue by BiligeYang** [leggedrobotics/RSLGym#1]
Hi. Cool work. I tried running the example cartpole with pfrl_ppo_train.py in the scripts. But I get the following error:

`Found pfrl. importing rslgym version of train_agent_batch_with_evaluation.
fatal: Failed to parse --submodule option parameter: 'diff'
Traceback (most recent call last):
  File "pfrl_ppo_train.py", line 189, in <module>
    main()
  File "pfrl_ppo_train.py", line 56, in main
    cfg_saver = ConfigurationSaver(log_dir, save_items, args)
  File "/home/billy/raisim_workspace/RSLGym/rslgym/algorithm/utils/helpers.py", line 24, in __init__
    self.save_git_information(self._data_dir)
  File "/home/billy/raisim_workspace/RSLGym/rslgym/algorithm/utils/helpers.py", line 55, in save_git_information
    f.write(subprocess.check_output("git diff --submodule=diff".split()))
  File "/home/billy/miniconda3/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/home/billy/miniconda3/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'diff', '--submodule=diff']' returned non-zero exit status 128.
`

I used a conda environment (on Ubuntu 16.04) instead of the virtual environment you suggested. Could that be the cause of the error? Thanks!

**Comment by PascalEgli** [comment]
the examples were tested with venv on ubuntu 20.04.
